### PR TITLE
Add a workflow release

### PR DESCRIPTION
**Pull request by Fuseteam**
create a release with a zip containing all the needed files

This will automatically create a github release on the creation of a `release-*` tag, 

if it's an annotated tag it will take the title and body from the annotation, otherwise it'll take it from the commit message

### CODE REVIEW

**Comment by electrikjesus** [comment]
I'll merge this from my laptop in a little bit to test

**Comment by Fuseteam** [comment]
Sounds good, i'm thinking of giving the zip a certain folder structure
```
wpm
|_bin
| |_wpm
|_share
  |_repos
```

What do you think?

**Comment by electrikjesus** [comment]
That should work just fine

**Comment by Fuseteam** [comment]
Kay lemme try to update the workflow for it

**Comment by Fuseteam** [comment]
Done xd

**Pull request merged**
