### PR TITLE
Generalize zip-it into it's own github action repo

### PR DESCRIPTION
**Pull request by Fuseteam**
* restructure the directory as bin share/wpm
* add an installation script; `wpm/wpm setup` will install wpm to the familiar directories
* wpm in the root is an installation script, the original wpm is in bin/wpm

### CODE REVIEW

**Comment by Fuseteam** [comment]
i know i said, this is ready for review, but now i'm getting a bunch of ideas :v
i'll leave a message here once i get through this surge

**Comment by Fuseteam** [comment]
Alright, this should do it
This enables installations with
```
wget https://github.com/waydroid/waydroid-package-manager/releases/latest/download/wpm.zip -O ~/Downloads/wpm.zip
unzip ~/Downloads/wpm.zip -d ~/wpm
~/wpm/wpm setup
```
removal with
```
source ~/.local/lib/crackle/wpm
remove_wpm
```
And even upgrades with
```
source ~/.local/lib/crackle/wpm
download_wpm
unzip_wpm
install_wpm
```

**Comment by electrikjesus** [comment]
Took me a minute to realize you already had tags all the way through version 1.0.12, so the release is on release-1.0.13

**Comment by Fuseteam** [comment]
> Took me a minute to realize you already had tags all the way through version 1.0.12, so the release is on release-1.0.13

Oh that's me doing release tests, didn't think it would reflect back 😅

**Comment by Fuseteam** [comment]
Actually i have a hard time believing my tags affected you, did you perhaps manually create the github release after merging the pr? I think that might've conflicted. 

I included an action that generates an github release based on the latest annotated tag, i can remove that action if it's too confusing

**Comment by electrikjesus** [comment]
That could have been it too then... Oh well. Just leave it as it is now and I can continue from 1.0.13 
The issue that Action was erroring on was that there was already a tag named 1.0.2, then 1.0.3, so I looked, and all the tags up to 1.0.12 were used... Figured those came from your side somehow

**Comment by Fuseteam** [comment]
Yeah the error is actually that there's already a release associated with that tag 🤔
Where did you see the tags were used btw, i'm positive i deleted most of the tags on my side

**Pull request merged**
